#ifndef __PARAMS__
#define __PARAMS__

#define MODMULTIPWMDRIVER_0_BASE_TON_REG 0
#define MODMULTIPWMDRIVER_0_BASE_NLATCH_REG 1
#define MODMULTIPWMDRIVER_0_BASE_OE_REG 2

#define PENDING_BUTTON 0
#define FALLING_BUTTON 1
#define RISING_BUTTON 2
#define PENDING_RISING_BUTTON 3

#define NONE_BLINKS 0
#define ON_OFF_BLINKS 1
#define T_ON_BLINKS 2
#define DIVIDE_FREQ_FOR_BLINKS 5

#define PWM_NUMBER 24
#define MAX_T_ON 1024

#define BYTES_BUS_NUMBER 32

#endif
